codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 1

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 90%
        threshold: 1%
        if_ci_failed: error
    patch:
      default:
        target: 90%
        threshold: 1%

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

ignore:
  - "test/**/*"
  - "dist/**/*"
  - "coverage/**/*"
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "vitest.config.ts"
  - "tsconfig.json"

flags:
  unittests:
    carryforward: true
    paths:
      - src/

